name: eeg_env
channels:
  - defaults
dependencies:
  - mne
  - python=3.8
  - numpy=1.22.4
  - pandas=1.3
  - matplotlib=3.4
  - scikit-learn=0.24
  - jupyter=1.0
  - torch
  - notebook
  - tqdm
  - torchvision
  - pip:
    - tensorflow==2.12.0
    - keras==2.4
    - seaborn==0.11
